============================
[debug] Begin to login ...
[debug] CAS response header True
[debug] Form url:  http://jkgc.hrbeu.edu.cn/infoplus/form/5624675/render
[debug] Form Status:  SUCCEED
[debug] Form stJson:  {'errno': 0, 'ecode': 'SUCCEED', 'entities': [{'stepId': 2, 'name': '办结', 'code': 'autoStep1', 'status': 0, 'type': 'Auto', 'flowStepId': 0, 'executorSelection': 0, 'timestamp': 0, 'posts': [], 'users': [], 'parallel': False, 'hasInstantNotification': False, 'hasCarbonCopy': False, 'entryId': 5556183, 'entryStatus': 0, 'entryRelease': False}]}
[info] Checkin succeed with jsoncode SUCCEED
[info] Task Finished at 2020-07-02 07:07:19 Thursday
============================

============================
[debug] Begin to login ...
[debug] CAS response header True
[debug] Form url:  http://jkgc.hrbeu.edu.cn/infoplus/form/5636081/render
[debug] Form Status:  EXCEPTION
[debug] Form stJson:  {'errno': 10000, 'ecode': 'EXCEPTION', 'error': 'java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 2 path $', 'entities': []}
[error] Checkin error with jsoncode EXCEPTION
[info] Task Finished at 2020-07-02 22:06:12 Thursday
============================

============================
[debug] Begin to login ...

[error] :.:.:.:.: Except return :.:.:.:.:
[error] Python Error: 
 Traceback (most recent call last):
  File "checkin.py", line 70, in <module>
    casRes = response302.history[0]
IndexError: list index out of range

[info] Task Finished at 2020-07-02 22:16:46 Thursday
============================

